### ISSUE TITLE
Break up questions by category

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#103]
Taking 38 questions in one go is not fun.  Find some way to break up this task into manageable chunks. 
**Categories**
- Transportation
- Economic Development
- City Engagement & Government
- Public Safety & Crime
- Sea Level Rise & The Environment
- Neighborhoods and Quality of Life
- Education

**Comment by ryayak1460** [comment]
We already split by categories, right? Couldn't we use the question attribute at the top and sort them accordingly?

**Comment by wbprice** [comment]
That's part of it.  I think the value in splitting the survey by category comes in reducing the perceived effort in finishing the survey.  Answering 7 questions in 5 categories isn't as bad as answering 35 questions in one go.  

We can add a button allow the user to skip to the next category when a minimum number of questions have been answered.  Wireframes for this to come.

**Comment by wbprice** [comment]
![category pager two lines](https://cloud.githubusercontent.com/assets/2590422/14819923/4b74650a-0b92-11e6-85be-6aefbc189ca1.png)

**Comment by wbprice** [comment]
![categories](https://cloud.githubusercontent.com/assets/2590422/18527258/ff2fa58c-7a91-11e6-89fc-111480ed6590.png)
