### ISSUE TITLE
Modify badges to change color based on match percentage.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#106]
In `atoms/CandidateMatchRating.jsx`, the background color of the container element is always red.  It would be helpful to show different colors based on the rating percentage.   Don't worry about specific colors or the ranges right now, we can adjust later based on the match data we start seeing.

**Scale**
0 - 50: 'red',
50-60: 'orange'
60-80: 'yellow'
80+: 'green'

**Comment by ryayak1460** [comment]
Implemented in #109.
