### ISSUE TITLE
Display a loading indicator when the app is grabbing survey questions or candidate matches.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#107]
In the global store, you have access to a flag `survey.isFetching` that can advise when an API call is taking place.  If `survey.isFetching` is true and the data we need for the given page is falsy, display a loading indicator and message.

Create a component `atom/LoadingIndicator` that contains a animated loading indicator and a message.  Implement on `ResultsPage.jsx` and `SurveyPage.jsx`

![loading survey](https://cloud.githubusercontent.com/assets/2590422/14561995/2147360c-02e8-11e6-89f4-5ce57234db1d.png)

**Survey Page:**
if `survey.isFetching` is true and `questions.length` is falsy, display loading message.
(half implemented at) https://github.com/Code4HR/okcandidate/blob/master/assets/js/components/ecosystems/SurveyPage.jsx#L65

**Results Page:**
if `survey.isFetching` is true and `Object.keys(survey.candidateMatch).length` is falsy, display loading message.

**Comment by ryayak1460** [comment]
On it.

**Comment by ryayak1460** [comment]
Added in #131, closing.
