### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/okcandidate#111]
Here's the snipit with new tracking ID included:

```javascript
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39303796-10', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by wbprice** [comment]
How granular is the data coming from this?  Will we know what people go to which pages and such?

**Comment by kmcurry** [comment]
Yep!

On Thu, Apr 14, 2016 at 11:08 PM, W. Blaine Price <notifications@github.com>
wrote:

> How granular is the data coming from this? Will we know what people go to
> which pages and such?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Code4HR/okcandidate/issues/111#issuecomment-210265968>
>



-- 
Kevin Curry
Virginia Beach, VA
https://www.comparityins.com
