### ISSUE TITLE
Candidates should be ranked in terms of match rating.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#127]

**Comment by ttavenner** [comment]
Is it possible at the same time to order by candidate type? On the ballot mayor will appear before council so it would make sense to do so on the site.

**Comment by ryayak1460** [comment]
Shouldn't we filter by position as well?

**Comment by wbprice** [comment]
@ryayak1460 Not sure what you mean.  Can you elaborate?
