### ISSUE TITLE
Google Analytics aren't working.

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/okcandidate#133]
React may need special handling with GA. [Current implementation](https://github.com/Code4HR/okcandidate/blob/master/views/Default.jsx#L8-L15) isn't [reporting data](https://analytics.google.com/analytics/web/#report/defaultid/a39303796w115084791p120319503/).

There are React Modules out there. This one seems popular https://github.com/react-ga/react-ga

First step is to just get it reporting someone landing on the entrypoint page. Then it would be awesome to track their progress through the questions to see how far they make it (will help see if people quit 1/2 way through). [This page at google](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications) talks about how to do that in GA with single page apps.

If anyone wants access to Analytics, let me know, I'd make it public if they had that option.

**Comment by ryayak1460** [comment]
Let's try that package.

If GA doesn't work, why not Dockerise Piwik?

On 21 April 2016 12:41:43 GMT-04:00, Bret Fisher <notifications@github.com> wrote:
>React may need special handling with GA. [Current
>implementation](https://github.com/Code4HR/okcandidate/blob/master/views/Default.jsx#L8-L15)
>isn't [reporting
>data](https://analytics.google.com/analytics/web/#report/defaultid/a39303796w115084791p120319503/).
>
>There are React Modules out there. This one seems popular
>https://github.com/react-ga/react-ga
>
>If anyone wants access to Analytics, let me know, I'd make it public if
>they had that option.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/issues/133

-- 
Ryan Y.
Software Design Engineer
Alion Science and Technology Corporation
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@dukgo.com

**Comment by BretFisher** [comment]
Oh I'm sure GA would work fine once we learn how to use it with React. Nothing wrong with Piwik, but it would be another thing we'd have to maintain, and then we have the years of data on all our properties in GA: ![](http://d.pr/i/18Q5O/251k9OKf+)

**Comment by ryayak1460** [comment]
No problem, makes sense.  Didn't consider maintenance.

I can take a look later tonight.

On 21 April 2016 14:50:24 GMT-04:00, Bret Fisher <notifications@github.com> wrote:
>Oh I'm sure GA would work fine once we learn how to use it with React.
>Nothing wrong with Piwik, but it would be another thing we'd have to
>maintain, and then we have the years of data on all our properties in
>GA: ![](http://d.pr/i/18Q5O/251k9OKf+)
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/issues/133#issuecomment-213062578

-- 
Ryan Y.
Software Design Engineer
Alion Science and Technology Corporation
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@dukgo.com
