### ISSUE TITLE
Abstract Google Analytics key

### ISSUE THREAD

**Issue by ryayak1460** [Code4HR/okcandidate#139]
In case we need to change the Google Analytics key in the future, and since we also don't want that information publicly available, let's go ahead and use the advantage of our Docker integration and use an environment variable to provide this value to the frontend.

Per @BretFisher, we will use `GOOGLE_ANALYTICS` as our environment variable to integrate with Docker.

**Comment by BretFisher** [comment]
Thanks for the PR Ryan. FYI GA is OK to be publically avail for anyone on any site that uses it, since it's in the .js downloaded to client browser. We just wanted it to be easily changeable per environment so this looks good for that.

**Comment by ryayak1460** [comment]
Okay, cool.  @wbprice merged the associated pull request, so closing this issue.
