### ISSUE TITLE
Va Beach - Who is running for office?

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#144]
Find names of people who are running for office and what offices they are running for.  Save this to the [wiki](https://github.com/Code4HR/okcandidate/wiki/Va-Beach-Research).

**Comment by stanzheng** [comment]
they can be found here. 

http://www.vpap.org/localities/virginia-beach-city-va/elections/tracked/

the races that we probably will be covered, bounding shapes probably required to be adjusted to. 

- Mayor
- General City Council
- Kempsville
- Rose hall

- Centerville Maybe if  candidate wishes to run
