### ISSUE TITLE
Va Beach - What offices are up for election? 

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#145]
Add this information to the [wiki](https://github.com/Code4HR/okcandidate/wiki/Va-Beach-Research)

**Comment by chrisruddick** [comment]
http://elections.virginia.gov/Files/CastYourBallot/CandidateList/20161108-NovGen-Local-List_of_Candidates_By_Office_Locality.pdf
http://elections.virginia.gov/Files/CastYourBallot/CandidateList/20161108-NovGen-State-List_of_Candidates_By_Office_District.pdf

**Comment by wbprice** [comment]
We will have four offices:
- Mayor
- City Council - At Large
- City Council - Centerville
- City Council - Kempsville
