### ISSUE TITLE
Va Beach - Add candidates to database

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#148]
- Mayor
    - George Furman III
    - Richard W. "RK" Kowalewitch
    - W. D. "Will" Sessoms, Jr.
    - A. M. "Don" Weeks
- City Council - At Large
    - Dane U. Blythe
    - Courtney L. LaLonde
    - Rosemary A. Wilson
    - Pam D. Witham
- City Council - Centerville
    - Robert M. "Bobby" Dyer
- City Council - Kempsville
    - Jessica P. Abbott
    - Amelia N. Ross-Hammond

**Comment by kmcurry** [comment]
Since I took the survey in production this must be done.
