### ISSUE TITLE
Convert to Sqlite from Postgres

### ISSUE THREAD

**Issue by stanzheng** [Code4HR/okcandidate#163]
Apart of #161 making the project easier to setup. Since we dont have a huge scale of data this would be a probably fine transition. We are also using bookshelf and knex so migrating should be not too difficult. 

It would solve a lot of the issues of schemas getting out of sync. Just dumping new schemas and updating a db file is much simpler and won't require any complicated setup.

1. Data more portable
2. Less setup cross platform on hack nights
3. Easier to keep in sync with schema changes

**Comment by ttavenner** [comment]
We probably won't be able to do this if we want to use any kind of GIS data for defining where a race is happening. Right now we are planning to add PostGIS into the mix. I will close this as won't fix for now but we can revisit it if it turns out we don't need GIS features.
