### ISSUE TITLE
Show matchability throughout the entire survey

### ISSUE THREAD

**Issue by mjalkio** [Code4HR/okcandidate#168]
Right now needing to answer over 30 questions before getting any information back is disheartening (I see this is also addressed in #103). Something that might help is showing your current matchability throughout the entire survey.

This is how it works on OkCupid too. You can choose to answer just a few questions and still see your matchability with different people, or you can answer more questions for a more accurate score.

How is matchability calculated? I can't find it in the code 😅

**Comment by wbprice** [comment]
Fixed in #195
