### ISSUE TITLE
Replace Questions Remaining Alert with Progress Bar

### ISSUE THREAD

**Issue by mjalkio** [Code4HR/okcandidate#169]
Right now there's the "X questions remaining" alert at the top of the page when you're taking the survey, but I think a progress bar would be more appropriate.

**Comment by wbprice** [comment]
![progress bar](https://cloud.githubusercontent.com/assets/2590422/18688096/d816949c-7f50-11e6-881d-bb071510ea42.png)

**Game Rules:**
- Level 1 - achieved by answering 1/3 of questions
- Level 2 - achieved by answering 2/3 questions
- Level 3 - achieved by answering all the questions.

**Behavior:**
- Progress bar describes number of questions that have been answered on this level.  When a new level is reached, it resets.
- Once user has reached at least level one, the current matches can be checked by clicking a submit button that appears.

Other thoughts:  
- Badges?
- Animations?

**Comment by wbprice** [comment]
![progress bar updated](https://cloud.githubusercontent.com/assets/2590422/18719905/5ffb587e-7ff7-11e6-9d91-dc7b4c19328a.png)

Same rules as above, but this has more character.
