### ISSUE TITLE
Questions that are not questions

### ISSUE THREAD

**Issue by mjalkio** [Code4HR/okcandidate#170]
I know that this isn't really an issue with the application but with how the application is being used, but maybe something can be done about it to make sure it doesn't happen in the future. There are two questions in the current survey that aren't questions:
<img width="334" alt="screen shot 2016-07-06 at 7 03 46 pm" src="https://cloud.githubusercontent.com/assets/3981503/17637962/b3553202-60ac-11e6-8729-1525c908f172.png">
<img width="387" alt="screen shot 2016-08-12 at 4 44 15 pm" src="https://cloud.githubusercontent.com/assets/3981503/17637965/b8937346-60ac-11e6-98c0-d0773cd86ed8.png">

It's really unclear (1) what exactly they want to ask and (2) how the hearts should be used while answering this question. Any thoughts?

**Comment by stanzheng** [comment]
Thanks @mjalkio for chiming in. We took this suggestion in and we made it, this time, to try and avoid this type of issue with our questions. Check out the #okcandidate channel for our new doc and feel free to weigh in if the case. Its also for VB so you would be an excellent guinea pig.

Happy to reopen if additional guidance
