### ISSUE TITLE
Questions where "how strongly do you feel" does not make sense

### ISSUE THREAD

**Issue by mjalkio** [Code4HR/okcandidate#171]
This is very similar to my last issue (#170) because it's not necessarily an issue with the application, only with how it's being used. There are two questions where "how strongly do you feel" doesn't seem applicable:
<img width="274" alt="screen shot 2016-07-06 at 7 03 59 pm" src="https://cloud.githubusercontent.com/assets/3981503/17638039/2bc1bb0c-60ad-11e6-9fb3-874f8f9e7684.png">
<img width="557" alt="screen shot 2016-08-12 at 4 43 53 pm" src="https://cloud.githubusercontent.com/assets/3981503/17638048/366d9c2e-60ad-11e6-9754-05697086d3e7.png">

The issue that might make sense to fix is to have the ability to add questions that do not use the "how strongly do you feel" hearts. But these questions also make me wonder how the matchability is being calculated. If I own a bike and a candidate owns a bike does the website give us a better score?

**Comment by ryayak1460** [comment]
We saw this as an issue to begin with as well.  I don't remember our resolution at the time.  Who recalls why we solved it this way?

On 12 August 2016 17:54:52 GMT-04:00, Michael Jalkio <notifications@github.com> wrote:
>This is very similar to my last issue (#170) because it's not
>necessarily an issue with the application, only with how it's being
>used. There are two questions where "how strongly do you feel" doesn't
>seem applicable:
><img width="274" alt="screen shot 2016-07-06 at 7 03 59 pm"
>src="https://cloud.githubusercontent.com/assets/3981503/17638039/2bc1bb0c-60ad-11e6-9fb3-874f8f9e7684.png">
><img width="557" alt="screen shot 2016-08-12 at 4 43 53 pm"
>src="https://cloud.githubusercontent.com/assets/3981503/17638048/366d9c2e-60ad-11e6-9754-05697086d3e7.png">
>
>The issue that might make sense to fix is to have the ability to add
>questions that do not use the "how strongly do you feel" hearts. But
>these questions also make me wonder how the matchability is being
>calculated. If I own a bike and a candidate owns a bike does the
>website give us a better score?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/issues/171

-- 
Ryan Y.
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@protingumas.com

**Comment by wbprice** [comment]
There was a disconnect between the format of the questions asked and the text of the questions.  This is mainly my bad for not coordinating with the Pilot question authors better.

**Comment by mjalkio** [comment]
So it's just something that the future question authors need to be prepped on more? Is there any need for education materials or things like that?

**Comment by ryayak1460** [comment]
Other than "pose questions assuming the answer will come in the form of a quantitative enumeration of feelings, not binary responses," no.

On 16 August 2016 11:04:55 GMT-04:00, Michael Jalkio <notifications@github.com> wrote:
>So it's just something that the future question authors need to be
>prepped on more? Is there any need for education materials or things
>like that?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/issues/171#issuecomment-240130788

-- 
Ryan Y.
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@protingumas.com

**Comment by stanzheng** [comment]
Thanks @mjalkio for chiming in. We took this suggestion in and we made it, this time, to try and avoid this type of issue with our questions. Check out the #okcandidate channel for our new doc and feel free to weigh in if the case. Its also for VB so you would be an excellent guinea pig.

Happy to reopen if additional guidance
