### ISSUE TITLE
Add ability to skip questions

### ISSUE THREAD

**Issue by mjalkio** [Code4HR/okcandidate#172]
Not everyone has a stance on every issue. Someone taking the survey should be able to skip questions or be provided an "I don't know" button.

I see that there was an issue months ago about preventing someone from skipping every question (#57) but it looks like the feature was completely removed. Why?

**Comment by ryayak1460** [comment]
You skip by clicking Next.

On 12 August 2016 17:57:56 GMT-04:00, Michael Jalkio <notifications@github.com> wrote:
>Not everyone has a stance on every issue. Someone taking the survey
>should be able to skip questions or be provided an "I don't know"
>button.
>
>I see that there was an issue months ago about preventing someone from
>skipping every question (#57) but it looks like the feature was
>completely removed. Why?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/issues/172

-- 
Ryan Y.
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@protingumas.com

**Comment by wbprice** [comment]
Adding an "I don't care about this" button should be trivial.  It could probably share a click handler with the "Next" button.

**Comment by ryayak1460** [comment]
Fair enough, I just explained the reasoning, not the future.

On 16 August 2016 10:02:40 GMT-04:00, "W. Blaine Price" <notifications@github.com> wrote:
>Adding an "I don't care about this" button should be trivial.  It could
>probably share a click handler with the "Next" button.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/issues/172#issuecomment-240111094

-- 
Ryan Y.
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@protingumas.com
