### ISSUE TITLE
Find photos for candidates

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#215]
Track down the best photos possible for each of the following candidates running for office in Virginia Beach, VA.

Mayor
  - [ ] George Furman III
  - [ ] Richard W. "RK" Kowalewitch
  - [ ] W. D. "Will" Sessoms, Jr.
  - [ ] A. M. "Don" Weeks

City Council - At Large
  - [ ] Dane U. Blythe
  - [ ] Courtney L. LaLonde
  - [ ] Rosemary A. Wilson
  - [ ] Pam D. Witham

City Council - Centerville
  - [ ] Robert M. "Bobby" Dyer

City Council - Kempsville
  - [ ] Jessica P. Abbott
  - [ ] Amelia N. Ross-Hammond

**Comment by neortls007idev** [comment]
taking it

**Comment by mridulg** [comment]
On it.
