### ISSUE TITLE
Modularize routes file

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#24]
Routes.js is already getting pretty gnarly.  Now that we have some interactions defined, we should start moving them into controllers.

**Comment by stanzheng** [comment]
i started working on this but ran into an issue modularizing the handlers because they make calls to the models through the server interface

**Comment by stanzheng** [comment]
in #35, pending @ttavenner for greenlight

**Comment by stanzheng** [comment]
we merged this lol
