### ISSUE TITLE
Intensity rating icons should be hearts

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#56]
<img width="461" alt="screen shot 2016-03-27 at 10 47 36 pm" src="https://cloud.githubusercontent.com/assets/2590422/14069910/f494dc8c-f46d-11e5-8d5d-c433698bd3f8.png">

**Comment by wbprice** [comment]
For reference: https://github.com/dreyescat/react-rating

**Comment by stanzheng** [comment]
Ryan added some hearts but they seem to be smaller than the original icons, might need adjustment in size 
![screenshot 2016-04-02 12 46 33](https://cloud.githubusercontent.com/assets/3683993/14227676/062f227e-f8d1-11e5-9db6-66fc9fac8ab6.png)

**Comment by ryayak1460** [comment]
#69 should have corrected the size and colours enough to close this.

**Comment by stanzheng** [comment]
looks good 
- they're the OKCandidate colors
- 54x54
- has some scales
