### ISSUE TITLE
Prevent user from skipping all the questions.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#57]

**Comment by wbprice** [comment]
Maybe don't display/disable the skip button until a minimum number of questions have been answered.

**Comment by mjalkio** [comment]
This was changed, right? I don't see any ability to skip a question on the survey now.

**Comment by ryayak1460** [comment]
You skip by clicking Next.  We figured they mean roughly the same thing.

On 12 August 2016 17:19:49 GMT-04:00, Michael Jalkio <notifications@github.com> wrote:
>This was changed, right? I don't see any ability to skip a question on
>the survey now.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/issues/57#issuecomment-239562492

-- 
Ryan Y.
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@protingumas.com
