### ISSUE TITLE
Hide nav buttons and make fonts bigger on mobile

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/okcandidate#74]
As a mobile survey respondent it might be hard to read the questions. While I'm taking the survey I don't need the buttons at the top (Select Ward, Survey, Results). It would be better to give more of the screen to the question and make the questions easier to read.
![img_4036](https://cloud.githubusercontent.com/assets/69151/14248370/571301d4-fa42-11e5-98ea-b5bd2e829890.PNG)

**Comment by wbprice** [comment]
Partially completed.  Could still make fonts bigger on mobile.
