### ISSUE TITLE
Updated Landing Page

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#83]
We should combine the landing page and the beginning of the survey into one.  
![landing page](https://cloud.githubusercontent.com/assets/2590422/14406235/46a4aa14-fe70-11e5-9498-6f1fd84721a4.png)
A condensed version of the marketing text would appear in three columns below the form for getting the user address.  Selecting a superward manually is presented as a fallback option if someone doesn't want to give an address.

**Comment by wbprice** [comment]
@jonhargreaves is going to provide an illustration for the background.

**Comment by wbprice** [comment]
@kmcurry Can you think of pithy marketing copy for the three columns?  Best I can come up with right now is: 
<img width="349" alt="screen shot 2016-04-10 at 3 06 24 am" src="https://cloud.githubusercontent.com/assets/2590422/14408599/5a96eec0-fec9-11e5-9c74-f5510249a202.png">

**Comment by kmcurry** [comment]
I don't think the tag line should be "Candidates Near You Want Your Vote".
That sounds like political advertising. It should be "Find the candidates
for local office who best match with you." I'll try to come up with
something for the 3 columns.

On Sun, Apr 10, 2016 at 3:07 AM, W. Blaine Price <notifications@github.com>
wrote:

> @kmcurry <https://github.com/kmcurry> Can you think of pithy marketing
> copy for the three columns? Best I can come up with right now is:
> [image: screen shot 2016-04-10 at 3 06 24 am]
> <https://cloud.githubusercontent.com/assets/2590422/14408599/5a96eec0-fec9-11e5-9c74-f5510249a202.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Code4HR/okcandidate/issues/83#issuecomment-207936697>
>



-- 
Kevin Curry
Virginia Beach, VA
https://comparityins.com

**Comment by kmcurry** [comment]
"Find out which candidates for local office are a match for you"

**Comment by kmcurry** [comment]
# Ask
Candidates and voters take a (our?) survey
# Match
We matching voters with candidates (using and algorithm?)
# Vote
Voters go to the polls knowing exactly who they want in every office
