### ISSUE TITLE
Profile pics for mayoral candidates

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#92]
We need social network style profile pictures for the following.  Ideally, the source images would be at least 200x200px, although they won't necessarily be displayed at that size.  Source images should be png if possible.

Will be used here: 
<img width="342" alt="screen shot 2016-04-12 at 10 56 00 am" src="https://cloud.githubusercontent.com/assets/2590422/14464548/2e38375a-009d-11e6-9f6c-5bbcd98ecba5.png">

- [x] Kenneth Cooper Alexander
- [x] Robert J. McCabe
- [x] Andy A. Protogyrou
- [x] Andria P. McClellan
- [x] Warren A. Stewart
- [x] Barclay C. Winn
- [x] Harry David Candela
- [x] G.W. "Billy" Cook, Jr.
- [x] Angelia Williams Graves
- [x] Kendrick J. Turner

**Comment by lynnaloo** [comment]
Andy A. Protogyrou

![andyp](https://cloud.githubusercontent.com/assets/1610195/14512392/aea4d050-01ac-11e6-87f4-65d1a2675529.jpg)

**Comment by yejodido** [comment]
Kenneth Cooper Alexander

![kca](https://cloud.githubusercontent.com/assets/5909827/14512534/d6d43e16-01ad-11e6-8241-baee02600ca2.png)

**Comment by lynnaloo** [comment]
Angelia Williams Graves

![angeliaw](https://cloud.githubusercontent.com/assets/1610195/14512674/1cb7dffe-01af-11e6-8d21-8a5fb3b35e27.jpg)

**Comment by washt** [comment]
Barclay C. Winn
![barclay](https://cloud.githubusercontent.com/assets/2917298/14513739/ea361d9e-01b7-11e6-9446-fd9201b8f8dc.png)

**Comment by washt** [comment]
Andria P. McClellan
![andrea](https://cloud.githubusercontent.com/assets/2917298/14513798/7257bb10-01b8-11e6-9f1a-7a324516e946.png)

**Comment by thecbliss** [comment]
Here's McCabe
![bobmccabe](https://cloud.githubusercontent.com/assets/9258699/14529501/dcac8558-0222-11e6-986b-eac134e6c924.jpg)

**Comment by ryayak1460** [comment]
Warren A. Stewart:
![stewartwa_37233](https://cloud.githubusercontent.com/assets/18220590/14533942/22099782-0235-11e6-86e7-3706df16e61b.jpg)

**Comment by ryayak1460** [comment]
Henry David Candela
![final_20160307](https://cloud.githubusercontent.com/assets/18220590/14534200/17a54b14-0236-11e6-8503-35aed5f27ea4.jpg)

**Comment by wbprice** [comment]
The image of Stewart is a little small.  Can you find a better one?

**Comment by ryayak1460** [comment]
The updated one's not better?

**Comment by wbprice** [comment]
Oh, I didn't see the update.

**Comment by ryayak1460** [comment]
G.W. Billy "Cook," Jr.:

![berkley-historic-district](https://cloud.githubusercontent.com/assets/18220590/14534769/9f64bca4-0238-11e6-8254-9b64e642d866.png)

**Comment by ryayak1460** [comment]
Best picture I can find of Kendrick Turner resides here:
<http://virginiapreachers.com/kendrick_turner.html>

**Comment by wbprice** [comment]
@ryayak1460 does Kendrick Turner have Twitter or something?

**Comment by ryayak1460** [comment]
He's a pastor in Newport News, from all I've read so far.

**Comment by ryayak1460** [comment]
Slightly bigger picture of Kendrick Turner:

![384977_102809419836101_585682543_n](https://cloud.githubusercontent.com/assets/18220590/14537872/00d5ecfc-0247-11e6-8851-aff85e6f7bfb.jpg)

**Comment by wbprice** [comment]
Win! Thanks everyone!
