### ISSUE TITLE
Results Page Category Dropdown

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#94]
In `organisms/CandidateMatchCandidate.jsx`:
Use an accordion element to hide or show category breakdown on candidate matches page.  Can be triggered with a caret icon.  
![dropdowns](https://cloud.githubusercontent.com/assets/2590422/14467504/9ec719c6-00a9-11e6-9275-1ecf041100da.png)
Clicking the caret icon toggles the value of `this.state.showCategory`.  The icon should change to reflect current state of `this.state.showCategory`
![accordion card](https://cloud.githubusercontent.com/assets/2590422/14470410/5b492212-00b7-11e6-9653-d8377e9519e6.png)

**Comment by ryayak1460** [comment]
#95 implements this.
